FROM python:3.11-slim-buster
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

WORKDIR /app

COPY main.py /app
COPY requirements.txt /app
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

CMD ["python", "main.py", "--host", "0.0.0.0", "--port", "80"]